# Generated by Django 3.1.4 on 2021-02-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='art_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
